### ISSUE TITLE
Netlify build previews faild

### ISSUE THREAD

**Issue by blackinno** [mesg-foundation/mesg-components#55]
- Netlify always asks packages from npm.
- Using ./netlify.sh
  ```bash 
  npm install ../packages/Theme
  npm install ../packages/Button
  npm install ../packages/Card
  npm install ../packages/Chart
  npm install ../packages/Footer
  npm install ../packages/Group
  npm install ../packages/Header
  npm install ../packages/Menu
  npm install ../packages/Newsletter
  npm install ../packages/Progressbar
  npm install ../packages/SideMenu
  npm install ../packages/Snackbar
  npm install ../packages/Tab
  npm install ../packages/Table
  npm install ../packages/TagLabel
  npm install
  npm run build
  ```
i have draft PR #54 with branch is issues/fix-build-preview-components.
On Netlify is using deploy command  ``` ./netlify.sh ```

**Comment by antho1404** [comment]
I fixed the issue with netlify and the installation directly on the PR https://github.com/mesg-foundation/mesg-components/pull/54.

@blackinno please have a look and let me know if you see any other issues
