### ISSUE TITLE
Create a header component

### ISSUE THREAD

**Issue by antho1404** [mesg-foundation/mesg-components#67]
# UI

<img width="1443" alt="Screen Shot 2019-10-23 at 12 11 25" src="https://user-images.githubusercontent.com/1783126/67359809-878f7e00-f58e-11e9-8784-3b26ac8be5fa.png">

# Usage

```html
<!-- Header with title, description and picture. 50% title + description and 50% for the picture -->
<Header title="my title" description="my description" image="https://..." />

<!-- Header with a slot to describe -->
<Header title="my title" image="https://...">
  <p>My description</p>
  <btn>xxx</btn>
</Header>

<!-- No picture, header in full width -->
<Header title="my title">
  <p>My description</p>
  <btn>xxx</btn>
</Header>
```

# Properties

- title: String (required) -> title to display on the header
- description: String (optional) -> description to display on the header
- image: String (optional) -> image to render on the right side of the header, **if not present, the title and description should take 100% of the width**.

# Slots

- default to display the description content. **Only rendered if description property is not set**.

# Events

none

**Comment by blackinno** [comment]
Done.
