### ISSUE TITLE
Create Progressbar component

### ISSUE THREAD

**Issue by blackinno** [mesg-foundation/mesg-components#69]
# UI

![Screen Shot 2562-10-24 at 17 43 23](https://user-images.githubusercontent.com/16553272/67538014-f2b09000-f707-11e9-9bb9-9fed96207ef1.png)
# Usage

Describe how to use the component

```html
<!-- Progressbar with value -->
<Progressbar value="xx" />

<!-- Progressbar with indeterminate -->
<Progressbar value="xx"  indeterminate />

<!--  Progressbar with custom color  -->
<Progressbar value="xx"  color="red" />
...
```

# Properties

List all the properties needed for the component:
- value: Number (required) -> value to display width on the progressbar
- indeterminate: Boolean (optional) -> indeterminate is animation of the progressbar
- color: String (optional) -> change color of the progressbar

# Slots

none

# Events

none

**Comment by antho1404** [comment]
- Missing type for `value` and `color` properties.
- We don't know the value to put? is it between 0 and 1, between 0 and 100?

Do we need to be able to set up the `color` and `backgroundColor` if we have the `info/warning/danger/success`

We could say that by default it's the purple like in the picture and then we have either just the success/danger/warning... or just the color/backgroundColor but not both.

@EmmanuelDrouin what do you think?

**Comment by blackinno** [comment]
@antho1404 we need to able to set up the `color` because if you see at ATD website we used a different color for each progress bar but we can remove `backgroundColor `

<img width="968" alt="Screen Shot 2562-10-25 at 11 12 38" src="https://user-images.githubusercontent.com/16553272/67542746-68245c80-f718-11e9-9769-dab4a8a4d2b2.png">

**Comment by antho1404** [comment]
Good point, in that case, we can keep only `color` and `backgroundColor` and remove `success/warning...`

**Comment by EmmanuelDrouin** [comment]
@antho1404 @blackinno we don't need to set up the background color, as this one is always the same and won't change. The only color that we need to set up is the color of the value.

**Comment by EmmanuelDrouin** [comment]
Done
