### ISSUE TITLE
Create Taglabel component

### ISSUE THREAD

**Issue by blackinno** [mesg-foundation/mesg-components#71]
# UI
<img width="197" alt="Screen Shot 2562-10-25 at 12 16 58" src="https://user-images.githubusercontent.com/16553272/67544905-7165f700-f721-11e9-9fcf-fa41f0660edb.png">

# Usage

Describe how to use the component

```html
<!-- Tag label default -->
<Tag>
 <i class="fa fas-xxx" /> My text
</Tag>

<!-- Tag label with type ["partner" | "community "] -->
<Tag type="community">
 <i class="fa fas-xxx" /> My text
</Tag>

...
```

# Properties

List all the properties needed for the component:

- **type**: `String` (optional) - `[ "partner" | "community" ]`

# Slots

- default slot

# Events

none.

**Comment by antho1404** [comment]
- would be great to have the background color optional (also renaming it just color)
- why having the title and icon as props when this can be done as a slot to make it simple

```html
<Tag>My text</Tag>
<Tag><i>icon</i>My text</Tag>
```

@EmmanuelDrouin how this will be used? can we just have specific types of tag like sucess/info/warning... or do we need to have the control on the color of the background?

**Comment by EmmanuelDrouin** [comment]
@antho1404 the tag will be use in 3 situations. 

![Screenshot 2019-10-25 at 14 42 01](https://user-images.githubusercontent.com/15095289/67552633-a419ea80-f735-11e9-82a0-fbe6fdde6db3.png)

Default, Partner and Community.

We use the Partner and community version of the tag in the showcase/use case.

The default tag will be use for all other situations like the contributor page, the marketplace, ...
In a generic purpose.

We need to be able to customize the color of the background and the color of the text, in case we want to create a new version of this tag for a specific use.

It's a good idea, we could use also the tag component for a success/info/warning case. Let's see in the future, we should not close this possibility.

The background color should be optional, like the icon. If the developer don't custom the tag, it will appear in the default style.

```html
So maybe something like this:

<Tag>My title</Tag>
<Tag type="partner">My title</Tag>
<Tag><i>icon</i>My text</Tag>
<Tag type="community"><i>icon</i>My text</Tag>

The icon should be position before the text in the tag label not after.
Like all the other links we have on the website.
```

**Comment by EmmanuelDrouin** [comment]
Finalized
