### ISSUE TITLE
Create Card component

### ISSUE THREAD

**Issue by blackinno** [mesg-foundation/mesg-components#73]
# UI

<img width="715" alt="Screen Shot 2562-10-25 at 12 41 52" src="https://user-images.githubusercontent.com/16553272/67545848-da02a300-f724-11e9-9123-4526822208af.png">

# Usage

Describe how to use the component

```html
<!-- Card with bordered thin background noShadow -->
<Card  bordered  thin background no-shadow >
   <div class="xxxx">
    <h1>Text Custom inside Card</h1>
   </div>
</Card>

<!-- Card with custom border bottom color-->
<Card bordered border-bottom-color="red" >
   <div class="xxxx">
    <h1>Text Custom inside Card</h1>
   </div>
</Card>

<!-- Card with custom background-->
<Card background >
   <div class="xxxx">
    <h1>Text Custom inside Card</h1>
   </div>
</Card>

...
```

# Properties

List all the properties needed for the component:
- **bordered**: `Boolean` (optional) - default false
- **thin**: `Boolean` (optional) - default false
- **background**: `String` (optional) - default `#fff`
- **noShadow**: `Boolean` (optional) - default false
- **borderBottomColor**: `String` (optional)  

# Slots

default slot

# Events

none.

**Comment by antho1404** [comment]
Why do we have a `background` and `backgroundColor`?

**Comment by blackinno** [comment]
@antho1404  because `background ` it displays a default background color on a card but if we want to custom background-color we just use ` backgroundColor`

**Comment by antho1404** [comment]
so let's have `background` that has by default the default background and that we can override

**Comment by blackinno** [comment]
done in https://github.com/mesg-foundation/mesg-components/pull/66
