### ISSUE TITLE
Create a tweet button

### ISSUE THREAD

**Issue by EmmanuelDrouin** [mesg-foundation/mesg-components#74]
# UI

<img width="162" alt="Screenshot 2019-10-25 at 15 02 22" src="https://user-images.githubusercontent.com/15095289/67553927-869a5000-f738-11e9-8a61-fb931f9779f0.png">

# Usage

The button will be display to allow user to share with a tweet some specific content or link. We gonna actually use it in the contributors table to allow them to share the last rewarded contributions to their community.

```html

<TweetButton
  text="my text"
  recommendedAccount="mesgfoundation"
  counter/>

```

# Properties
- **text**: `String` required - Text that will be publish on twitter
- **recommandedAccount**: `String` optional - "mesgfoundation" added by default
- **counter**: `Boolean` optional - false by default

# Slots

none

# Events

none

# Docs
- https://publish.twitter.com/#
- https://developer.twitter.com/en/docs/twitter-for-websites/tweet-button/overview

**Comment by antho1404** [comment]
The implementation changed on https://github.com/mesg-foundation/mesg-components/pull/79.

- `counter` property is not present (and always set to false)
- There is a new `url` property to put an url in the tweet (so the text should not contain any url)
