### ISSUE TITLE
Create pagination component

### ISSUE THREAD

**Issue by EmmanuelDrouin** [mesg-foundation/mesg-components#82]
# UI

![Screenshot 2019-10-31 at 16 41 46](https://user-images.githubusercontent.com/15095289/67935970-7df4be80-fbfd-11e9-8766-ebb29f73901e.png)

# Usage

The component should allow the user to display a certain amount of items, regarding a selection (10, 20, 30, ...). The user should be able to navigate between all items by changing the page inside the element (for example in a table)

```html

<Pagination numberToDisplay="30" />

```

# Properties

List all the properties needed for the component:
- **numberToDisplay**: `String` optional -> the number of items to display by default is 10. we should be able to choose the amount of items we want to display (example 20 instead of 10).

# Slots

none

# Events

none

**Comment by antho1404** [comment]
we need a lot more information for this kind of component.

### Properties
- **page**: `number` (required) -> current page
- **totalPage**: `number` (required) -> total number of pages
- **perPage**: `number` (optional) -> default 10, the number of items per page to display

### Events
- `@pageChanged(page)`: when a page changed

the `page` and `@pageChanged` could be replaced with a `v-model` (`value` and `@input`)

**Comment by EmmanuelDrouin** [comment]
I would like to be able to choose what i want to use in the component.

We should have something allowing us to use just the ~~"sort by"~~ "number of item to display", or just the "pagination", or both at the same time.

Sometime we may need to display only the ~~sort by~~ "number of item to display", or only the pagination without the ~~sort by~~ "number of item to display" for example.

**Comment by antho1404** [comment]
Sorting is something independent of the pagination. It doesn't impact the pagination so it has no reason to be here. I think you're confused with the `table` component that could have some sorting on the columns but the pagination is not linked to that.

**Comment by EmmanuelDrouin** [comment]
~~@antho1404 ok so you should create another component for that?~~

**Comment by EmmanuelDrouin** [comment]
I think they are connecting together, no? I mean the ~~sorting option~~ "number of item to display" will impact the pagination. Example instead of displaying 10 elements, has a user i change the option to display 20 elements, it's gonna impact the number of page (gonna be less pages if you display 10 elements).

**Comment by EmmanuelDrouin** [comment]
Edited my previous posts, my mistake i was talking about "number of item to display" not "sort by"
