### ISSUE TITLE
Create TypeForm component

### ISSUE THREAD

**Issue by EmmanuelDrouin** [mesg-foundation/mesg-components#83]
# UI

TypeForm popup opening on click

![Screenshot 2019-11-04 at 18 19 44](https://user-images.githubusercontent.com/15095289/68117367-b6fb9e80-ff2f-11e9-8212-b191f775ab58.png)

# Usage

The component will open a popup based on an id.

**The component should be open in a popup and not in another page.**

```html

<!-- One way to use it -->
<TypeformPopup id="feaf3guf2">
  <a>click to open</a>
</TypeformPopup>

```

# Properties

List all the properties needed for the component:
- **id**: `Boolean` required -> id of the form

# Slots

- **default**: We should be able to customize the text inside the button or the link. On click open the popup. It's the activator of the popup.

# Events

none

# Code example

```html

<template>
  <Button
    primary
    class="typeform-share button"
    href="https://mesgfoundation.typeform.com/to/bOJ0qz"
    data-mode="popup"
    data-submit-close-delay="0"
  >Add contribution</Button>
</template>

<script>
import Button from "@mesg-components/button";
export default {
  components: {
    Button
  },
  mounted() {
    (function() {
      var qs,
        js,
        q,
        s,
        d = document,
        gi = d.getElementById,
        ce = d.createElement,
        gt = d.getElementsByTagName,
        id = "typef_orm_share",
        b = "https://embed.typeform.com/";
      if (!gi.call(d, id)) {
        js = ce.call(d, "script");
        js.id = id;
        js.src = b + "embed.js";
        q = gt.call(d, "script")[0];
        q.parentNode.insertBefore(js, q);
      }
    })();
  }
};
</script>

```

**Comment by antho1404** [comment]
I don't understand a few things in this component.

- What's the difference between the `form` property and `id` property?
- Why do we need a `type` for the form?
- Why a slot `text` when you describe it in your example as a default slot?
- Do you want a component that displays the popup of the form or do you want a button that opens the form?

**Comment by EmmanuelDrouin** [comment]
@antho1404 

- The `form` property will be the name that we gonna give to each form to choose which one to display with our component depending of the situation. Example in a situation i want to display the form "add contribution" so in the component i will do something like `form="add-contribution"`.

For that we need to get the `id` from this form. My idea was that it will be two different things. The `id` property will be use in the back-end of the component to get the form requested in the `form` property which will be use in the front-end.

- The `type` is more like a `class` attribute, so you can choose to display the link version of the component, or the purple button or the white button. Depending of the situation.

- The slot `text` is to be able to customize the content of the link/button.

- aah i know what you mean. I get confuse because the TypeForm embed works with a button already inside the component. But maybe it's better to have just a component that display the popup form which we can had inside a button component when we want to use it.

So if we do that we just need to get the `id` of each form and a property to display the one we want. We don't need to bother with being able to customize the link/button.

**Comment by EmmanuelDrouin** [comment]
Spec of the component updated regarding my last discussion with @antho1404 
@blackinno can you manage to have this component ready for the end of today?

**Comment by EmmanuelDrouin** [comment]
Done #85
